# Generated by Django 3.2.8 on 2021-10-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created'], 'verbose_name_plural': 'To Do'},
        ),
    ]
